title: Digital Graphics Foundations
description: Foundations, principles, and practical exercises in digital graphic design
url: "https://hanocat.github.io"
baseurl: "/digital-graphics-foundations"

markdown: kramdown